title: UniFi hosting - UniFi in the cloud as SaaS provider
baseURL: /
params:
  footer:
    content: '&copy; Modelit Andrzej Sibik. All rights reserved.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links: []
    logo_img: /images/unifi-hosting-white.png
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: Modelit Andrzej Sibik EU VAT ID PL9690000731
  header:
    has_nav: true
    logo_img: /images/unifi-hosting-orange.png
    title: UniFi Hosting.
    menu:
      actions:
        - label: Sign Up
          url: /signup
  palette: orange
disableKinds:
  - RSS
